# Generated by Django 5.1.4 on 2026-04-19 07:20

import secrets
import string

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _gen_ref(Indent):
    digits = string.digits
    d = django.utils.timezone.localdate().strftime("%Y%m%d")
    for _ in range(30):
        suffix = "".join(secrets.choice(digits) for _ in range(6))
        candidate = f"IND-{d}-{suffix}"
        if not Indent.objects.filter(public_reference_id=candidate).exists():
            return candidate
    return f"IND-{d}-{secrets.token_hex(4).upper()}"


def fill_public_reference_ids(apps, schema_editor):
    Indent = apps.get_model("ps", "Indent")
    for indent in Indent.objects.filter(public_reference_id__isnull=True):
        indent.public_reference_id = _gen_ref(Indent)
        indent.save(update_fields=["public_reference_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ps", "0006_indent_delivery_confirmed_and_stock_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="indent_attachments/%Y/%m/")),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="indentitem",
            name="uniq_item_per_indent",
        ),
        migrations.AddField(
            model_name="indent",
            name="contacts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="indent",
            name="date_of_request",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="indent",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="indent",
            name="expected_usage",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="indent",
            name="public_reference_id",
            field=models.CharField(
                editable=False, max_length=40, null=True, blank=True
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="urgency_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="why_requirement_needed",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(fill_public_reference_ids, noop_reverse),
        migrations.AlterField(
            model_name="indent",
            name="public_reference_id",
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name="indentitem",
            name="category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="indentitem",
            name="line_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="indentitem",
            name="line_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="indentitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="indentitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indent_lines",
                to="ps.storeitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="indentitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item__isnull", False)),
                fields=("indent", "item"),
                name="uniq_item_per_indent_when_item_set",
            ),
        ),
        migrations.AddField(
            model_name="indentdocument",
            name="indent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="ps.indent",
            ),
        ),
    ]
