# Generated by Django 4.2.24 on 2026-04-19 14:11

from django.db import migrations
import psmodule.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0007_indent_extended_fields_and_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='contacts',
            field=psmodule.models.JSONTextField(blank=True, default=list),
        ),
    ]
