# Generated by Django 5.1.4 on 2026-04-20 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0008_alter_indent_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_HOD_REVIEW', 'Under HOD Review'), ('STOCK_CHECKED', 'Stock Checked'), ('INTERNAL_ISSUED', 'Internal Issued'), ('EXTERNAL_PROCUREMENT', 'External Procurement'), ('FORWARDED_TO_DIRECTOR', 'Forwarded to Director'), ('APPROVED_BY_DEP_ADMIN', 'Approved by Dept Admin'), ('APPROVED', 'Approved'), ('STOCKED', 'Stocked'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('BIDDING', 'Bidding'), ('PURCHASED', 'Purchased'), ('STOCK_ENTRY', 'Stock Entry'), ('STOCK_ALLOCATED', 'Stock Allocated')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting_role', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to=settings.AUTH_USER_MODEL)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='ps.indent')),
            ],
        ),
        migrations.CreateModel(
            name='StockAllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocation_lines', to='ps.storeitem')),
                ('stock_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ps.stockallocation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_allocation', 'item'), name='uniq_item_per_stock_allocation')],
            },
        ),
    ]
