# Generated by Django 3.1.5 on 2026-04-20 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps1', '0002_assignment7'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('present_stock', models.IntegerField()),
                ('estimated_cost', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('purpose', models.CharField(max_length=250)),
                ('specification', models.CharField(max_length=250)),
                ('item_type', models.CharField(max_length=250)),
                ('item_subtype', models.CharField(default='computers', max_length=250)),
                ('nature', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('replaced', models.BooleanField(default=False)),
                ('budgetary_head', models.CharField(max_length=250)),
                ('expected_delivery', models.DateField()),
                ('sources_of_supply', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'IndentItem',
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AuditLog_timesta_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AuditLog_user_ti_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='AuditLog_entity__idx',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='budgetary_head',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='indigenous',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_subtype',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='present_stock',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='replaced',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='sources_of_supply',
        ),
        migrations.RemoveField(
            model_name='indentfile',
            name='specification',
        ),
        migrations.AddField(
            model_name='indentfile',
            name='approved_by',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indentfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indentfile',
            name='indent_name',
            field=models.CharField(default='Untitled Indent', max_length=250),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='AuditLog_timesta_5ad64d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='AuditLog_user_id_1038af_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='AuditLog_entity__e66c05_idx'),
        ),
        migrations.AddField(
            model_name='indentitem',
            name='indent_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ps1.indentfile'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ps1.indentitem'),
        ),
    ]
